name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      readme_path:
        required: true
        type: string
      docker_repository:
        required: true
        type: string
    secrets:
      DOCKER_BITSACCO_OWNER:
        required: true
      DOCKER_HUB_PUBLISH_TOKEN:
        required: true
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        required: false
      NEXT_PUBLIC_SANITY_DATASET:
        required: false
      NEXT_PUBLIC_SUPPORT_WHATSAPP:
        required: false
      NEXT_PUBLIC_SUPPORT_EMAIL:
        required: false
      NEXT_PUBLIC_APP_URL:
        required: false
      NEXT_PUBLIC_PARTNERS_FORM_URL:
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            okjodom/bitsacco-${{ inputs.docker_repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Get latest image tag
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        id: get-tag
        run: |
          echo "tag=$(echo '${{ steps.meta.outputs.tags }}' | head -n1)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_BITSACCO_OWNER }}
          password: ${{ secrets.DOCKER_HUB_PUBLISH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.dockerfile_path }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
            NEXT_PUBLIC_SANITY_DATASET=${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
            NEXT_PUBLIC_SUPPORT_WHATSAPP=${{ secrets.NEXT_PUBLIC_SUPPORT_WHATSAPP }}
            NEXT_PUBLIC_SUPPORT_EMAIL=${{ secrets.NEXT_PUBLIC_SUPPORT_EMAIL }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            NEXT_PUBLIC_PARTNERS_FORM_URL=${{ secrets.NEXT_PUBLIC_PARTNERS_FORM_URL }}

      - name: Update the Docker Hub description
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_BITSACCO_OWNER }}
          password: ${{ secrets.DOCKER_HUB_PUBLISH_TOKEN }}
          repository: okjodom/bitsacco-${{ inputs.docker_repository }}
          readme-filepath: ${{ inputs.readme_path }} 