name: publish-web

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - package-lock.json
      - apps/web/**
      - packages/**
      - .github/workflows/publish-web.yml
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - package-lock.json
      - apps/web/**
      - packages/**
      - .github/workflows/publish-web.yml

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  lint-test-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint --workspace=@bitsacco/web
        
      - name: Run tests
        run: npm run test --workspace=@bitsacco/web --if-present
        
      - name: Build application
        run: npm run build:web

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_BITSACCO_OWNER }}
          password: ${{ secrets.DOCKER_HUB_BITSACCO_PUBLISH_TOKEN }}
          
      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_BITSACCO_OWNER }}/web:latest
            ${{ secrets.DOCKER_BITSACCO_OWNER }}/web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_SUPPORT_WHATSAPP=${{ secrets.NEXT_PUBLIC_SUPPORT_WHATSAPP }}
            NEXT_PUBLIC_SUPPORT_EMAIL=${{ secrets.NEXT_PUBLIC_SUPPORT_EMAIL }}
